/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.DB;
import VALIDATE.Validation;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.LookAndFeel;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.xswingx.PromptSupport;
import org.jvnet.substance.SubstanceDefaultLookAndFeel;
import org.jvnet.substance.painter.GradientWaveGradientPainter;
import org.jvnet.substance.theme.SubstanceAquaTheme;
import org.jvnet.substance.watermark.SubstanceFabricWatermark;
import static sun.security.jgss.GSSUtil.login;

/**
 *
 * @author Damith
 */
public class GRN extends javax.swing.JFrame {

    /**
     * Creates new form GRN
     */
    public GRN() {
        initComponents();
        words();
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        clerText();
        showDate();
        showTime();
        autogen();
        //customCursor();
        //setDefaultCloseOperation(Home.DISPOSE_ON_CLOSE);
    }

//    public void customCursor(){
//        Toolkit tk = Toolkit.getDefaultToolkit();
//        Image img = tk.getImage("cursor.png");
//        Point point = new Point(0, 0);
//        Cursor customcursor = tk.createCustomCursor(img, point, "Cursor");
//        setCursor(customcursor);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Supplire_ID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_productID = new javax.swing.JTextField();
        Unit_Price = new javax.swing.JTextField();
        Quantity = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Searchfield2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        Supplier_name = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Searchfiled1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        Product_Name = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Sub_Total = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(255, 153, 153));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Good Received Note");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 11, -1, 32));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("GRN No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 144, 112, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Quantity", "Unit Price", "Sub Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 317, 672, 221));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("Unit Price");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Supplire ID");

        Supplire_ID.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("Product ID");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("Quantity(gram)");

        txt_productID.setEditable(false);

        Unit_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Unit_PriceActionPerformed(evt);
            }
        });
        Unit_Price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Unit_PriceKeyTyped(evt);
            }
        });

        Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityActionPerformed(evt);
            }
        });
        Quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuantityKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Supplire_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_productID, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(Unit_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Unit_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_productID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(Supplire_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 196, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Searchfield2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Searchfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Searchfield2ActionPerformed(evt);
            }
        });
        Searchfield2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Searchfield2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Searchfield2KeyTyped(evt);
            }
        });
        jPanel2.add(Searchfield2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 30));

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jList2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jList2KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 190, 110));

        Supplier_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Searchfiled1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Searchfiled1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Searchfiled1ActionPerformed(evt);
            }
        });
        Searchfiled1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Searchfiled1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Searchfiled1KeyTyped(evt);
            }
        });
        jPanel1.add(Searchfiled1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 30));

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jList1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 190, 110));

        Product_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(Supplier_name, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Product_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Product_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Supplier_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 54, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 10, 0, 0));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 0, 78, 43));

        Date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 222, 43));

        Time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Time.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 222, 26));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Minimize Window_30px.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 30, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Close Window_30px.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 30, 30));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 0, -1, -1));

        jPanel8.setBackground(new java.awt.Color(255, 204, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Sub Total");

        Sub_Total.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setText("Save");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Sub_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Sub_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, -1, 120));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Searchfiled1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Searchfiled1KeyReleased

        try {
            ResultSet rs = DB.search("select name from stock where name like '" + Searchfiled1.getText() + "%'");

            Vector v = new Vector();
            while (rs.next()) {

                jScrollPane1.setVisible(true);
                v.add(rs.getString("name"));

            }
            jList1.setListData(v);
            if (Searchfiled1.getText().isEmpty()) {
                jScrollPane1.setVisible(false);
            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
                jList1.grabFocus();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_Searchfiled1KeyReleased

    private void jList1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                ResultSet rs = DB.search("select name from stock where name='" + jList1.getSelectedValue().toString() + "'");
                while (rs.next()) {
                    Searchfiled1.setText(rs.getString("name"));
                    String s = Searchfiled1.getText();
                    Product_Name.setText(s);

                }

                ResultSet rs1 = DB.search("select sid from stock where name='" + jList1.getSelectedValue().toString() + "'");
                while (rs1.next()) {
                    txt_productID.setText(rs1.getString("sid"));
                    jScrollPane1.setVisible(false);
                    Searchfiled1.setText("");
                    Unit_Price.requestFocus();

                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jList1KeyReleased

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        try {
            ResultSet rs = DB.search("select name from stock where name='" + jList1.getSelectedValue().toString() + "'");
            while (rs.next()) {
                Searchfiled1.setText(rs.getString("name"));
                String s = Searchfiled1.getText();
                Product_Name.setText(s);

            }

            ResultSet rs1 = DB.search("select sid from stock where name='" + jList1.getSelectedValue().toString() + "'");
            while (rs1.next()) {
                txt_productID.setText(rs1.getString("sid"));
                jScrollPane1.setVisible(false);
                Searchfiled1.setText("");
                Unit_Price.requestFocus();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jList2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList2KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                ResultSet rs = DB.search("select fname from supplier where fname='" + jList2.getSelectedValue().toString() + "'");
                //
                while (rs.next()) {
                    Searchfield2.setText(rs.getString("fname"));
                    String s = Searchfield2.getText();
                    Supplier_name.setText(s);

                }

                ResultSet rs1 = DB.search("select id from supplier where fname='" + jList2.getSelectedValue().toString() + "'");
                while (rs1.next()) {
                    Supplire_ID.setText(rs1.getString("id"));
                    jScrollPane2.setVisible(false);
                    Searchfield2.setText("");
                    Searchfiled1.requestFocus();
                }
            } catch (Exception ex) {

                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_jList2KeyReleased

    private void Searchfield2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Searchfield2KeyReleased
        try {
            ResultSet rs = DB.search("select fname from supplier where fname like '" + Searchfield2.getText() + "%'");
            //
            Vector v = new Vector();

            while (rs.next()) {
                jScrollPane2.setVisible(true);
                v.add(rs.getString("fname"));
            }

            jList2.setListData(v);

            if (Searchfield2.getText().isEmpty()) {
                jScrollPane2.setVisible(false);
            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
                jList2.grabFocus();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Searchfield2KeyReleased

    private void Searchfiled1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Searchfiled1ActionPerformed
    }//GEN-LAST:event_Searchfiled1ActionPerformed

    private void Unit_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Unit_PriceActionPerformed
        Quantity.requestFocus();
    }//GEN-LAST:event_Unit_PriceActionPerformed

    private void Searchfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Searchfield2ActionPerformed

    }//GEN-LAST:event_Searchfield2ActionPerformed

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        try {
            ResultSet rs = DB.search("select fname from supplier where fname='" + jList2.getSelectedValue().toString() + "'");
            //
            while (rs.next()) {
                Searchfield2.setText(rs.getString("fname"));
                String s = Searchfield2.getText();
                Supplier_name.setText(s);

            }

            ResultSet rs1 = DB.search("select id from supplier where fname='" + jList2.getSelectedValue().toString() + "'");
            while (rs1.next()) {
                Supplire_ID.setText(rs1.getString("id"));
                jScrollPane2.setVisible(false);
                Searchfield2.setText("");
                Searchfiled1.requestFocus();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jList2MouseClicked
    DecimalFormat df = new DecimalFormat("#0.##");
    private void QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        Double a = Double.parseDouble(Quantity.getText());
        Double b = Double.parseDouble(Unit_Price.getText());
        Double c = a * b;

        Vector v = new Vector();

        v.add(txt_productID.getText());
        v.add(Product_Name.getText());
        v.add(Quantity.getText());
        v.add(Unit_Price.getText());
        v.add(c);
        dtm.addRow(v);

        Double sub = 0.0;

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sub += Double.parseDouble(dtm.getValueAt(i, 4).toString());
            Sub_Total.setText("" + sub + "0");
            Unit_Price.setText("");
            Quantity.setText("");
            jTextField2.grabFocus();

        }


    }//GEN-LAST:event_QuantityActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int x = 0;
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        try {

            for (int i = 0; i < jTable1.getRowCount(); i++) {
                String pid = jTable1.getValueAt(i, 0).toString();
                String p_name = jTable1.getValueAt(i, 1).toString();
                String quantity = jTable1.getValueAt(i, 2).toString();
                String unit_price = jTable1.getValueAt(i, 3).toString();
                System.out.println(unit_price);
                String sub_total = jTable1.getValueAt(i, 4).toString();

                DB.iud("insert into grn (supplier_id, supplier_name, product_name, qty, unit_price,  date, time) values "
                        + "('" + Supplire_ID.getText() + "', '" + Supplier_name.getText() + "', '" + p_name + "', '" + quantity + "', '" + unit_price + "',  '" + Date.getText() + "', '" + Time.getText() + "')");

                ResultSet rs = DB.search("select gid from grn where gid='" + jTextField1.getText() + "'");
                if (rs.next()) {
                    x = Integer.parseInt(rs.getString("gid").toString());
                }

                DB.iud("insert into grn_item(stock_sid, grn_gid, product_name, unit_price, qty, total, sub_total, date, time) values "
                        + "('" + pid + "', '" + x + "', '" + p_name + "', '" + unit_price + "', '" + quantity + "', '" + sub_total + "','" + Sub_Total.getText() + "','" + Date.getText() + "', '" + Time.getText() + "')");
                //

                ResultSet rsz = DB.search("SELECT  * FROM stock s  WHERE s.name = '" + p_name + "' AND s.qty = '' AND s.unit_price = ''");
                if (rsz.first()) {
                    DB.iud("update stock set qty=qty+'" + quantity + "',unit_price='" + unit_price + "', buying_price='" + Sub_Total.getText() + "' where sid='" + rsz.getString("sid") + "'");
                } else {
                    DB.iud("INSERT INTO stock (name,qty,unit_price,buying_price) VALUES ('" + p_name + "','" + quantity + "','" + unit_price + "','" + sub_total + "')");
                }

            }
            JOptionPane.showMessageDialog(rootPane, "GRN HAS SAVED!");

        } catch (Exception e) {
            e.printStackTrace();
        }

        dtm.setRowCount(0);
        clerText();
        autogen();
        this.dispose();
        MenuForm m = new MenuForm();
        m.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        this.dispose();
        MenuForm f = new MenuForm();
        f.setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        Searchfield2.grabFocus();
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void Searchfield2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Searchfield2KeyTyped
        Validation.isCharacter(evt);
        Validation.checkLength(evt, Searchfield2.getText(), 15);
    }//GEN-LAST:event_Searchfield2KeyTyped

    private void Searchfiled1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Searchfiled1KeyTyped
        Validation.isCharacter(evt);
        Validation.checkLength(evt, Searchfiled1.getText(), 15);
    }//GEN-LAST:event_Searchfiled1KeyTyped

    private void Unit_PriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Unit_PriceKeyTyped
        Validation.isNumaric(evt);
        Validation.checkLength(evt, Unit_Price.getText(), 15);
    }//GEN-LAST:event_Unit_PriceKeyTyped

    private void QuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityKeyTyped
        Validation.isNumaric(evt);
        Validation.checkLength(evt, Quantity.getText(), 15);
    }//GEN-LAST:event_QuantityKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    //UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");

//                    LookAndFeel look=new SubstanceDefaultLookAndFeel(); 
//                    UIManager.setLookAndFeel(look);
//                    SubstanceDefaultLookAndFeel.setCurrentTheme(new SubstanceAquaTheme());
//                    SubstanceDefaultLookAndFeel.setCurrentWatermark(new SubstanceFabricWatermark());
//                    SubstanceDefaultLookAndFeel.setCurrentGradientPainter(new GradientWaveGradientPainter());
//                    GRN.setDefaultLookAndFeelDecorated(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                new GRN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Product_Name;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTextField Searchfield2;
    private javax.swing.JTextField Searchfiled1;
    private javax.swing.JLabel Sub_Total;
    private javax.swing.JLabel Supplier_name;
    private javax.swing.JTextField Supplire_ID;
    private javax.swing.JLabel Time;
    private javax.swing.JTextField Unit_Price;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txt_productID;
    // End of variables declaration//GEN-END:variables

    private void words() {

        PromptSupport.setPrompt("Search product...", Searchfiled1);
        PromptSupport.setPrompt("Search supplier...", Searchfield2);

    }

    private void clerText() {
        Supplire_ID.setText("");
        txt_productID.setText("");
        Unit_Price.setText("");
        Quantity.setText("");
        Sub_Total.setText("");

    }

    private void showDate() {
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("EEE, d MMM yyyy");
        String s = sdf.format(d);
        Date.setText(s);

    }

    private void showTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("h:mm:ss a");
                String s = sdf.format(d);
                Time.setText(s);
            }
        }).start();

    }

    private void autogen() {
        try {
            ResultSet rs = DB.search("select max(gid) from grn");

            while (rs.next()) {
                int i = rs.getInt("max(gid)");
                jTextField1.setText(i + 1 + "");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
