/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import DB.DB;
import VALIDATE.Validation;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.xswingx.PromptSupport;

/**
 *
 * @author Damith
 */
public class GRN_details extends javax.swing.JFrame {
    
    int timeRun = 0;

    /**
     * Creates new form GRN_details
     */
    public GRN_details() {
        initComponents();
        jScrollPane1.setVisible(false);
        clerText();
        //customCursor();
        search();
        
       // setDefaultCloseOperation(Home.DISPOSE_ON_CLOSE);
        
        
    }
    
//    public void customCursor(){
//        Toolkit tk = Toolkit.getDefaultToolkit();
//        Image cursorimg = tk.getImage("Cursor-Neon.png");
//        Point cursorHotsPot = new Point(0,0);
//        Cursor customcursor = tk.createCustomCursor(cursorimg, cursorHotsPot, "Cursor");
//        setCursor(customcursor);
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        searchfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        radio_grn = new javax.swing.JRadioButton();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        Supplire_Name = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        panela = new javax.swing.JPanel();
        balance = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchfield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchfieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchfieldKeyTyped(evt);
            }
        });
        jPanel1.add(searchfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 35));

        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jList1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 220, -1));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 1070, 570));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 253, 214));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Unit Price", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 1033, 265));

        buttonGroup1.add(radio_grn);
        radio_grn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_grn.setText("Search GRN ID");
        getContentPane().add(radio_grn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        Date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 36, 162, 30));

        Time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 88, 160, 32));

        Supplire_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Supplire_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 110, 150, 33));
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 31, 170, 35));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 11, -1, 2));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Close Window_30px.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 30, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Minimize Window_30px.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 30, 30));

        jButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton2.setText("Print");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, 100, 35));

        panela.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        balance.setEditable(false);

        jLabel4.setText("Sub Total");

        javax.swing.GroupLayout panelaLayout = new javax.swing.GroupLayout(panela);
        panela.setLayout(panelaLayout);
        panelaLayout.setHorizontalGroup(
            panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelaLayout.createSequentialGroup()
                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelaLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelaLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(326, 326, 326))
        );
        panelaLayout.setVerticalGroup(
            panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panela, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 190, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    private void searchfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchfieldKeyReleased
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        if(radio_grn.isSelected()){
            
          try {
           ResultSet rs= DB.search("select distinct grn_gid from grn_item where grn_gid like '"+searchfield.getText()+"%'");
            Vector v = new Vector();
            while (rs.next()) { 
                jScrollPane1.setVisible(true);
                v.add(rs.getString("grn_gid"));
                
            }
            jList1.setListData(v);
            
            if(searchfield.getText().length()==0){
                jScrollPane1.setVisible(false);
            }
            
            if(evt.getKeyCode()==KeyEvent.VK_DOWN){
                jList1.grabFocus();
            }
            
            if(searchfield.getText().length()==0){
               dtm.setRowCount(0);
               clerText();         
                    
                    }
            
        } catch (Exception e) {
            e.printStackTrace();
            }
            
        }else{
          
      
            
        }      
        
    }//GEN-LAST:event_searchfieldKeyReleased

    private void jList1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyReleased
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        
        if(radio_grn.isSelected()){
            if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                 if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                try {
                
//                DB.search("select grn.Supplire_Name, grn.Product_Name, grn.Quantity, grn.Unit_Price, grn.Discount, grn.Net_Total, grn.Cash, grn.balance, grn_registry.date, grn_registry.time from grn INNER JOIN grn_registry ON grn.GRN_No= grn_registry.'"+jList1.getSelectedValue().toString()+"'");
//                while (DB.rs.next()) { 
//                    
//                    Vector v = new Vector();
//                    
//                    v.add(DB.rs.getString("Product_Name"));
//                    v.add(DB.rs.getString("Quantity"));
//                    v.add(DB.rs.getString("Unit_Price"));
//                    
//                    dtm.addRow(v);
//                    
//                    Discount.setText(DB.rs.getString("Discount"));
//                    net_total.setText(DB.rs.getString("Net_Total"));
//                    cash.setText(DB.rs.getString("Cash"));
//                    balance.setText(DB.rs.getString("balance"));
//                    Date.setText(DB.rs.getString("date"));
//                    Time.setText(DB.rs.getString("time"));
//                    Supplire_Name.setText(DB.rs.getString("Supplire_Name"));
//                    
//                    jScrollPane1.setVisible(false);
//                }
                    
                    ResultSet rs=DB.search("select * from grn_item where grn_gid='"+jList1.getSelectedValue().toString()+"'");
                    while (rs.next()) {                        
                        Vector v = new Vector();
                        
                        v.add(rs.getString("product_name"));
                        v.add(rs.getString("qty"));
                        v.add(rs.getString("unit_price"));
                       v.add(rs.getString("total"));
                       
                        
                        dtm.addRow(v);
                          balance.setText(rs.getString("sub_total"));
                        
                    }
                    
                    ResultSet rs1=DB.search("select * from grn where gid='"+jList1.getSelectedValue().toString()+"'");
                    while (rs1.next()) {      
                        
//                        Discount.setText(rs1.getString("discount"));
//                        net_total.setText(rs1.getString("net_total"));
//                        cash.setText(rs1.getString("cash"));
                     

                        
                       
                        Date.setText(rs1.getString("date"));
                        Time.setText(rs1.getString("time"));
                        Supplire_Name.setText(rs1.getString("supplier_name"));
                        
                        jScrollPane1.setVisible(false);
                    }
                
            } catch (Exception e) {
                e.printStackTrace();
                
                }
            
            }
            
        }else{
            
            }
        
        }
    }//GEN-LAST:event_jList1KeyReleased

    private void searchfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchfieldKeyTyped

        Validation.isNumaric(evt);
        Validation.checkLength(evt,searchfield.getText(),15);
    }//GEN-LAST:event_searchfieldKeyTyped

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        this.dispose();
      MenuForm f=new MenuForm();
      f.setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try {
            InputStream jr =GRN_details.class.getResourceAsStream("/Report/grn_details.jasper");
            HashMap hm = new HashMap();
            hm.put("id", searchfield.getText());
           // hm.put("supplier_name", searchfield.getText());
            JasperPrint jp = JasperFillManager.fillReport(jr, hm, DB.getConnection());
          JasperViewer.viewReport(jp,false);
            JasperPrintManager.printReport(jp, true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GRN_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GRN_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GRN_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GRN_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GRN_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Supplire_Name;
    private javax.swing.JLabel Time;
    private javax.swing.JTextField balance;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panela;
    private javax.swing.JRadioButton radio_grn;
    private javax.swing.JTextField searchfield;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables

    private void clerText() {
        
        
     
       
        Supplire_Name.setText("");
        Date.setText("");
        Time.setText("");
    }

    private void search() {
        PromptSupport.setPrompt("search...", searchfield);
    }

}
