/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.DB;
import VALIDATE.Validation;
import java.awt.Color;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kaveesha Nadun
 */
public class Supplier extends javax.swing.JFrame {

    /**
     * Creates new form Employee_Details
     */
    public Supplier() {
        initComponents();
        generateId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ad = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        cty = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        cn = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        src = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        save = new javax.swing.JButton();
        clear_table = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        load = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setText("Search By ID");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("Supplier Details");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 220, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Minimize Window_30px.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 30, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Close Window_30px.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 30, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Contact No");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Supplier ID");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("FName");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 60, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("LName");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 60, -1));

        ad.setColumns(20);
        ad.setRows(5);
        ad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(ad);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 330, 50));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Address");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 70, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("City");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 40, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Email ID");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 70, -1));

        sid.setEditable(false);
        sid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sidKeyTyped(evt);
            }
        });
        jPanel2.add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 180, -1));

        fn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnKeyTyped(evt);
            }
        });
        jPanel2.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 180, -1));

        ln.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lnKeyTyped(evt);
            }
        });
        jPanel2.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 180, -1));

        cty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ctyKeyTyped(evt);
            }
        });
        jPanel2.add(cty, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 180, -1));

        em.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emKeyReleased(evt);
            }
        });
        jPanel2.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 180, -1));

        cn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cnKeyTyped(evt);
            }
        });
        jPanel2.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 180, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Search By ID");
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, -1));

        src.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srcKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                srcKeyTyped(evt);
            }
        });
        jPanel2.add(src, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 210, -1));

        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, -1, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 0), 4));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 10, 230));

        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 0), 4));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 610, 10));

        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 0), 4));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 88, 630, 10));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 0), 4));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 10, 240));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "FName", "LName", "Address", "City", "Email ID", "Contact No"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 920, 180));

        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setText("Save");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 70, -1));

        clear_table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear_table.setText("Clear Table");
        clear_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear_tableMouseClicked(evt);
            }
        });
        jPanel2.add(clear_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, -1, -1));

        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        jPanel2.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, -1, -1));

        load.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        load.setText("Load ALL");
        load.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadMouseClicked(evt);
            }
        });
        jPanel2.add(load, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/164935537-wood-wallpapers.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 950, 540));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
         this.dispose();
      MenuForm f=new MenuForm();
      f.setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        String id=sid.getText();
       String name=fn.getText();
       String name1=ln.getText();
       String add=ad.getText();
       String city=cty.getText();
       String email=em.getText();
       String cont=cn.getText();
      
       


       
        try{
            
           if(DB.iud("insert into supplier values('"+id+"','"+name+"','"+name1+"','"+add+"','"+city+"','"+email+"','"+cont+"')")) {
            //sid.setText(null);
            fn.setText(null);
            ln.setText(null);
            ad.setText(null);
            cty.setText(null);
            em.setText(null);
            cn.setText(null);
            
            generateId();
           }else{ 
             JOptionPane.showMessageDialog(this, "cannot insert duplicate supplier id"," ", JOptionPane.WARNING_MESSAGE);
           }
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       
    }//GEN-LAST:event_saveActionPerformed

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        String id=sid.getText();
       String name=fn.getText();
       String name1=ln.getText();
       String add=ad.getText();
       String city=cty.getText();
       String email=em.getText();
       String cont=cn.getText();
    
       
        try {
            DB.iud("update supplier set fname='"+name+"',lname='"+name1+"',address='"+add+"' ,city='"+city+"' ,email='"+email+"',contact='"+cont+"'  where id='"+id+"'");
            //sid.setText(null);
            fn.setText(null);
            ln.setText(null);
            ad.setText(null);
            cty.setText(null);
            em.setText(null);
            cn.setText(null);
            src.setText(null);
        
            generateId();
            save.setEnabled(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
      try {
          
       
            if(DB.iud("delete from supplier where id='"+sid.getText()+"'")){
            
            sid.setText(null);
            fn.setText(null);
            ln.setText(null);
            ad.setText(null);
            cty.setText(null);
            em.setText(null);
            cn.setText(null);
            src.setText(null);
        
            generateId();
            save.setEnabled(true);
          
             
          
            }else{
                 JOptionPane.showMessageDialog(this, "cannot delete used  supplier"," ", JOptionPane.WARNING_MESSAGE);
            }
      }catch (Exception e) {
          
          e.printStackTrace();
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        try {
              
      ResultSet rs=DB.search("select * from supplier where id='"+src.getText()+"'");
            if(rs.next()) {
                
                sid.setText(rs.getString("id"));
                fn.setText(rs.getString("fname"));
                ln.setText(rs.getString("lname"));
                ad.setText(rs.getString("address"));
                cty.setText(rs.getString("city"));
                em.setText(rs.getString("email"));
                cn.setText(rs.getString("contact"));
                
                  if(Integer.parseInt(sid.getText())==Integer.parseInt(src.getText())){
save.setEnabled(false);
                  }
             
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchMouseClicked

    private void clear_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_tableMouseClicked
        DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
         sid.setText(null);;
            fn.setText(null);
            ln.setText(null);
            ad.setText(null);
            cty.setText(null);
            em.setText(null);
            cn.setText(null);
            src.setText(null);
           
            generateId();
            save.setEnabled(true);
        
    }//GEN-LAST:event_clear_tableMouseClicked

    private void loadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadMouseClicked
       try {
            ResultSet rs=DB.search("select * from supplier");
            DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            while (rs.next()){
                Vector v=new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
               
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_loadMouseClicked

    private void sidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sidKeyTyped
       Validation.isNumaric(evt);
        Validation.checkLength(evt,sid.getText(),15);
    }//GEN-LAST:event_sidKeyTyped

    private void fnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnKeyTyped
      Validation.isCharacter(evt);
        Validation.checkLength(evt,fn.getText(),15);
    }//GEN-LAST:event_fnKeyTyped

    private void lnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnKeyTyped
       Validation.isCharacter(evt);
        Validation.checkLength(evt,ln.getText(),15);
    }//GEN-LAST:event_lnKeyTyped

    private void adKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adKeyTyped
      
        Validation.checkLength(evt,ad.getText(),40);
    }//GEN-LAST:event_adKeyTyped

    private void ctyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctyKeyTyped
     
        Validation.checkLength(evt,cty.getText(),15);
    }//GEN-LAST:event_ctyKeyTyped

    private void emKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emKeyReleased
        String valideml = Validation.isValidemail(em.getText());
        //Validation.checkLength(evt,eml.getText(),15);
        if (valideml.equals("Valid Email ID")) {
            em.setForeground(Color.BLACK);
        } else {
            em.setForeground(Color.RED);
        }
    }//GEN-LAST:event_emKeyReleased

    private void cnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnKeyTyped
       Validation.isNumaric(evt);
        Validation.checkLength(evt,cn.getText(),10);
    }//GEN-LAST:event_cnKeyTyped

    private void srcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srcKeyTyped
      Validation.isNumaric(evt);
        Validation.checkLength(evt,src.getText(),15);
    }//GEN-LAST:event_srcKeyTyped

    private void srcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srcKeyReleased
       save.setEnabled(true);
    }//GEN-LAST:event_srcKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ad;
    private javax.swing.JButton clear_table;
    private javax.swing.JTextField cn;
    private javax.swing.JTextField cty;
    private javax.swing.JButton delete;
    private javax.swing.JTextField em;
    private javax.swing.JTextField fn;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField ln;
    private javax.swing.JButton load;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTextField sid;
    private javax.swing.JTextField src;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

   private void generateId() {
        try {
            ResultSet r = DB.search("SELECT MAX(id) FROM supplier");
            if (r.next()) {
               
                    sid.setText(String.valueOf(r.getInt(1) + 1));
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
